#!/usr/bin/env python3
"""
generate_permutations.py
Regenerates selection_kernel.hpp for the conjunctive selection ablation study.
Based on: Ross, "Conjunctive Selection Conditions in Main Memory" (PODS 2002)

Usage:
    python3 generate_permutations.py > selection_kernel.hpp
    python3 generate_permutations.py --output path/to/selection_kernel.hpp

Predicates and column names can be edited in the PREDICATES and COLUMNS
lists below. The accumulator expression can be edited in ACCUMULATOR.
"""

import argparse
import sys
from itertools import permutations

# ---------------------------------------------------------------------------
# Edit these to match your predicates.
# The index variable used inside each predicate expression (here 'i') must
# match whatever loop variable your existing code uses.
# ---------------------------------------------------------------------------

PREDICATES = [
    "l_shipdate[i] >= c1",   # P0
    "l_shipdate[i] < c2",    # P1
    "l_quantity[i] < c5",    # P2
    "l_discount[i] >= c3",   # P3
    "l_discount[i] <= c4",   # P4
]

# ---------------------------------------------------------------------------

def generate(out):
    perms = list(permutations(range(len(PREDICATES))))
    n_perms = len(perms)

    def w(line=""):
        out.write(line + "\n")

    w("// AUTO-GENERATED by generate_permutations.py — do not edit by hand")
    w("// Defines SELECTION_CONDITION(i) for TPC-H Q6 predicate ablation study.")
    w("// Based on: Ross, \"Conjunctive Selection Conditions in Main Memory\" (PODS 2002)")
    w(f"// {n_perms} permutations x 2 operator variants = {n_perms * 2} total configurations")
    w()
    w("// Usage in your existing code:")
    w("//   #include \"selection_condition.hpp\"")
    w("//   if (SELECTION_CONDITION(i)) { ... }")
    w()
    w("#pragma once")
    w()
    w("// Base build fallback: if no ablation defines are provided, the original")
    w("// hardcoded expression is used and no ablation behaviour is active.")
    w("#ifndef OPERATOR_VARIANT")
    w("#  define OPERATOR_VARIANT -1")
    w("#endif")
    w("#ifndef PERMUTATION_INDEX")
    w("#  define PERMUTATION_INDEX -1")
    w("#endif")
    w()
    w("#if OPERATOR_VARIANT == -1")
    w("// Base build: operator selection is encoded in PERMUTATION_INDEX == -1 below")
    w("#elif OPERATOR_VARIANT == 0")
    w("#  define CONJUNCT_OP &")
    w("#elif OPERATOR_VARIANT == 1")
    w("#  define CONJUNCT_OP &&")
    w("#else")
    w('#  error "OPERATOR_VARIANT must be 0 (BITWISE) or 1 (SHORT_CIRCUIT)"')
    w("#endif")
    w()

    for idx, perm in enumerate(perms):
        keyword = "#if" if idx == 0 else "#elif"
        ordered = [PREDICATES[p] for p in perm]
        condition = " CONJUNCT_OP \\\n        ".join(f"({p})" for p in ordered)
        perm_label = " ".join(f"P{p}" for p in perm)
        w(f"{keyword} PERMUTATION_INDEX == {idx}")
        w(f"// Permutation {idx}: {perm_label}")
        w(f"#  define SELECTION_CONDITION(i) \\")
        w(f"        ({condition})")

    w("#elif PERMUTATION_INDEX == -1")
    w("// Base build: original hardcoded expression, no ablation active")
    base_condition = " & \\\n        ".join(f"({p})" for p in PREDICATES)
    w(f"#  define SELECTION_CONDITION(i) \\")
    w(f"        ({base_condition})")
    w("#else")
    w(f'#  error "PERMUTATION_INDEX must be between 0 and {n_perms - 1}"')
    w("#endif")
    w()
    w("// CONJUNCT_OP is an implementation detail; do not use it directly.")
    w("#undef CONJUNCT_OP")

def main():
    parser = argparse.ArgumentParser(description="Generate selection_kernel.hpp")
    parser.add_argument("--output", "-o", default=None,
                        help="Output file (default: stdout)")
    args = parser.parse_args()

    if args.output:
        with open(args.output, "w") as f:
            generate(f)
        print(f"Written to {args.output}", file=sys.stderr)
    else:
        generate(sys.stdout)

if __name__ == "__main__":
    main()
